### ISSUE TITLE
Add contribution guide/support non-WSL dev environments

### ISSUE THREAD

**Issue by NoPhaseNoKill** [13k/invokation#37]
Hey,

I'd like to be able to contribute to this repo - but currently it looks like it only supports WSL. 

Questions:
1. Am I able to contribute from a non-WSL environment? Currently it looks like I require WSL - whereas I'd rather just use my normal linux setup
2. Is the current version of the development.md file up to date?
3. Is it worth adding a contributing.md for steps of how someone might contribute to your project?
4. It's also unclear from the development.md file exactly what the path should be. Is it worth adding an example or two? ie: if dota2 is installed at this directory, then your dota2 path should be: XYZ etc (added via edit)

Feel free to add any additional suggestions/things to look out for here, so I can start contributing :)

**Comment by 13k** [comment]
>     1. Am I able to contribute from a non-WSL environment? Currently it looks like I require WSL - whereas I'd rather just use my normal linux setup

I'm a primarily Linux user, so I get where you are coming from. [I tried](https://github.com/13k/dota2-tools-proton) to use Dota 2's workshop tools[1] on Linux but I gave up.

The minimum requirement is to run `resourcecompiler.exe` to compile maps, scripts and assets. It is a CLI tool and would be perfect for running inside a docker container with steamcmd + dota2 tools + proton. It turns out it depends on Direct3D and the container must run with a GPU context, which is doable but complicates a lot the docker setup and after an updated to the tools by Valve, it stopped working with the executable crashing and I was too lazy to debug docker + gpu + wine + direct3d.

The next best thing was using WSL on Windows.

>     2. Is the current version of the development.md file up to date?

Is is (as of 8727ca0fde6ee6ae69be5ada9d00b7d09da182f6).

>     3. Is it worth adding a contributing.md for steps of how someone might contribute to your project?

There's no demand for it, you're the first to demonstrate interest in contributing.

>     4. It's also unclear from the development.md file exactly what the path should be. Is it worth adding an example or two? ie: if dota2 is installed at this directory, then your dota2 path should be: XYZ etc (added via edit)

Good idea. I will update `DEVELOPMENT.md` with some examples.

> Feel free to add any additional suggestions/things to look out for here, so I can start contributing :)

Thanks a lot for showing interest and sorry for the extremely delayed response from me. I don't have much time to maintain the game any longer, so I come here very sporadically to only check if the game is broken by Valve updates and fix only these kind of issues.

I guess the project is in maintenance mode for a long time now, so I guess contributions would both help but also be very delayed to get merged.
